server:
  port: 4000
spring:
  application:
    name: crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
#  redis:
#    host: 127.0.0.1
#  session:
#    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

short:
  message:
    app-code: 927359fdc6ad457182fc0a73ca521d42
    host: https://largesms.market.alicloudapi.com
    path: /largesms
    sign: 175622
    skin: 1
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
